# Generated by Django 4.2.2 on 2023-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
